### ISSUE TITLE
Audio recording capabilities

### ISSUE THREAD

**Issue by georgeke** [uwblueprint/dancefest-mobile#38]
Need support for
- audio recording
- pausing a recording
- resuming a recording

Need to try out some of these libraries and see what works best

Possible libraries we can use:
1. [`react-native-audio-toolkit`](https://github.com/futurice/react-native-audio-toolkit) (usage [here](https://github.com/futurice/react-native-audio-toolkit/blob/master/docs/API.md))
2. [`react-native-audio`](https://github.com/jsierles/react-native-audio)

**Comment by jtaaa** [comment]
Another possibility is using [Expo's audio API](https://docs.expo.io/versions/latest/sdk/audio.html)
