### ISSUE TITLE
Audio file cloud storage

### ISSUE THREAD

**Issue by georgeke** [uwblueprint/dancefest-mobile#40]
Figure out where we want to store it and build the API calls needed to do the online uploading.

**Comment by jtaaa** [comment]
Looking into this guide https://cmichel.io/google-drive-in-react-native

**Comment by jtaaa** [comment]
Something to think about is that we will need to have the user login to a Google account at some point

**Comment by katrinacrisostomo** [comment]
@jtaaa make sure the file names are set (both in the phone and in google drive) :D
